call main.py index.html
call main.py smileys.html
call main.py people.html
call main.py component.html
call main.py animals.html
call main.py food.html
call main.py travel.html
call main.py activities.html
call main.py objects.html
call main.py symbols.html
call main.py flags.html